 name: Build Android APK

  on:
    push:
      branches: [main, master, develop]
    pull_request:
      branches: [main, master]
    workflow_dispatch:

  jobs:
    build:
      name: Build APK
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Prepare APK files
        run: |
          mkdir -p outputs
          find app/build/outputs/apk -name "*.apk" -exec cp {} outputs/ \;
          cd outputs
          for file in *.apk; do
            if [[ $file == *"debug"* ]]; then
              mv "$file" "TKJY-QuestionSystem-debug-${{ steps.date.outputs.date }}.apk"
            elif [[ $file == *"release"* ]]; then
              mv "$file" "TKJY-QuestionSystem-release-${{ steps.date.outputs.date }}.apk"
            fi
          done
          ls -la

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TKJY-QuestionSystem-APKs-${{ steps.date.outputs.date }}
          path: outputs/*.apk
          retention-days: 30
